/**
 * Credits.
 *
 * Short, honest, and readable in one screen. It names the parts of the game
 * that are genuinely interesting to have built rather than padding a list.
 */

import { CHAMPIONSHIPS, TRACKS } from '../../track/library';
import { SHIPS } from '../../game/ships';
import type { Screen, UiContext } from '../context';
import { el, hintBar, screenFrame } from '../widgets';

interface Block {
  role: string;
  name: string;
  body?: string;
  list?: string[];
}

export function createCreditsScreen(_ctx: UiContext): Screen {
  const frame = screenFrame({ title: 'Credits', kicker: 'Pulsar Circuit' });
  const root = el('div', 'vh-screen');
  root.appendChild(frame.root);

  const blocks: Block[] = [
    {
      role: 'Engine',
      name: 'WebGPU, with a WebGL2 fallback',
      body: 'Rendering, post-processing and materials are authored once in TSL and run on either backend, so the game looks the same on hardware that has no WebGPU driver.',
    },
    {
      role: 'Circuits',
      name: `${TRACKS.length} handbuilt tracks`,
      body: 'Each one is authored as a list of driving instructions — turn, climb, roll, loop — rather than as geometry, so a corner can be tuned by what it asks of the player.',
      list: TRACKS.map((t) => `${t.name} — ${t.tagline}`),
    },
    {
      role: 'Craft',
      name: `${SHIPS.length} racing hulls`,
      body: 'Handling numbers are in real units, so the spread between the roster is something you can reason about instead of something that was dialled in blind.',
      list: SHIPS.map((s) => `${s.name} — ${s.manufacturer}`),
    },
    {
      role: 'Series',
      name: `${CHAMPIONSHIPS.length} championships`,
      list: CHAMPIONSHIPS.map((c) => `${c.name} — ${c.tagline}`),
    },
    {
      role: 'Audio',
      name: 'Synthesised at runtime',
      body: 'Every engine note, impact and music cue is generated by the Web Audio graph. There are no audio files anywhere in the build.',
    },
    {
      role: 'Interface',
      name: 'No assets, no fonts, no icons',
      body: 'Every mark on screen is drawn as inline SVG or a CSS gradient, and the type is a system stack. Nothing here waits on a network request.',
    },
  ];

  const wrap = el('div', 'vh-credits vh-stagger');
  blocks.forEach((block, index) => {
    const section = el('section', 'vh-credits__block');
    section.style.setProperty('--i', String(index));
    section.appendChild(el('p', 'vh-credits__role', block.role));
    section.appendChild(el('h2', 'vh-credits__name', block.name));
    if (block.body) section.appendChild(el('p', 'vh-credits__body', block.body));
    if (block.list) {
      const list = el('ul', 'vh-credits__list');
      for (const entry of block.list) list.appendChild(el('li', '', entry));
      section.appendChild(list);
    }
    wrap.appendChild(section);
  });
  frame.body.appendChild(wrap);

  frame.footer.appendChild(hintBar([{ keys: ['Esc'], label: 'Back' }]));

  return { root };
}
